spring.application.name=sistema-salgados

spring.datasource.generate-unique-name=false
spring.datasource.name=coxinhadb

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
